[server]
headless = true
address = "0.0.0.0"
enableCORS = false
enableXsrfProtection = false

[browser]
gatherUsageStats = false

[theme]
primaryColor="#8B0000"
backgroundColor="#FDFBF7"
secondaryBackgroundColor="#F0EAD6"
textColor="#2C2C2C"
font="serif"
